feat(support, serde): Bits
recmo/uint pull request #203
Opened 2022-11-01 11:01 UTC by shekhirin

## Motivation

## Solution

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Updated the changelog

2022-11-01 18:03 UTC, recmo requested changes

2022-11-01 18:03 UTC, recmo commented on src/support/serde.rs
> +        deserializer.deserialize_str(StrVisitor).map(Self::from)
The same forwarding will work here too.

2022-11-02 12:10 UTC, shekhirin commented on src/support/serde.rs
> +        serializer.serialize_str(&result)
agree, such impl will be better. fixed.

2022-11-02 18:01 UTC, recmo approved these changes

2022-11-02 18:02 UTC, merged