Add support for Subtle and DER.
recmo/uint pull request #399
Opened 2024-10-14 10:33 UTC by recmo

## Motivation

Makes it easier to use UInts for implementing cryptographic protocols.

## Solution

## PR Checklist

- [x] Added Tests
- [ ] Added Documentation
- [ ] Updated the changelog

2024-10-15 12:35 UTC, prestwich commented
let me know when this is ready for review 👍

2024-11-01 06:13 UTC, recmo commented
@prestwich Ready for review!

2024-11-01 18:31 UTC, prestwich requested changes
mostly no_std compilation related changes

2024-11-01 18:31 UTC, prestwich commented on src/support/der.rs
> +// `Any::new()` only retutns error when length > u32:MAX, which is out of scope
nit: typo `retutns` here, on L115, and L!32

2024-11-01 18:31 UTC, prestwich commented on src/support/der.rs
> +use std::cmp::Ordering;
import should be from core to avoid breaking on no_std

2024-11-01 18:31 UTC, prestwich commented on Cargo.toml
> +]
needs explicit features for `der = ["dep:der", "alloc"]` and `subtle = ["dep:subtle"]

2024-11-04 02:35 UTC, recmo commented
@prestwich Please review!

I did look briefly in adding a 'does it build in `no_std`' step to the CI, but it seems that as of today there are still no good solutions to test this. But the clippy lint I added should cover the majority of problems.

2024-11-04 13:00 UTC, merged